# Generated by Django 4.2.11 on 2024-04-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQs', 'Multiple Choice'), ('TF', 'True/False'), ('SA', 'Short Answer')], default='MCQs', max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizapp.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='per_question_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
