# Generated by Django 4.2.11 on 2024-04-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_remove_question_topic_question_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correctAnswer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
    ]
