# Generated by Django 4.2.11 on 2024-04-07 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
