# Generated by Django 4.2.11 on 2024-04-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='per_question_score',
            new_name='perQuestionScore',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='total_questions',
            new_name='totalQuestions',
        ),
    ]
